set windows-shell := ["pwsh.exe", "-NoLogo", "-Command"]
set ignore-comments := true

default:
  @just --list


export_container_image := "kicad_export:latest"

# Export the given project. E.g. `just export OpenMI`
export project: _prepare-export
  podman run --rm \
  --volume "{{justfile_directory() / project}}:/workspace:rw" \
  {{export_container_image}} export {{project}}

_prepare-export:
  podman build \
  --tag {{export_container_image}} \
  {{justfile_directory() / '.container'}}
